common:
  run_label: "run_1"
  log_freq: 500
  auto_resume: true
  mixed_precision: True
  results_loc: "/home/disk/result/classification_imagenet1k/edgeformer-s"
dataset:
  root_train: "/home/disk/data/imagenet1k/training"
  root_val: "/home/disk/data/imagenet1k/validation"
  name: "imagenet"
  category: "classification"
  train_batch_size0: 128
  val_batch_size0: 64
  eval_batch_size0: 64
  workers: 8
  persistent_workers: false
  pin_memory: true
image_augmentation:
  random_resized_crop:
    enable: true
    interpolation: "bilinear"
  random_horizontal_flip:
    enable: true
sampler:
  name: "variable_batch_sampler"
  vbs:
    crop_size_width: 256
    crop_size_height: 256
    max_n_scales: 5
    min_crop_size_width: 160
    max_crop_size_width: 320
    min_crop_size_height: 160
    max_crop_size_height: 320
    check_scale: 32
loss:
  category: "classification"
  classification:
    name: "label_smoothing"
    label_smoothing_factor: 0.1
optim:
  name: "adamw"
  weight_decay: 0.025
  no_decay_bn_filter_bias: false
  adamw:
    beta1: 0.9
    beta2: 0.999
scheduler:
  name: "cosine"
  is_iteration_based: false
  max_epochs: 300
  warmup_iterations: 3000
  warmup_init_lr: 0.0004
  cosine:
    max_lr: 0.004
    min_lr: 0.0004
model:
  classification:
    name: "edgeformer"
    classifier_dropout: 0.2
    edge:
      scale: "scale_s"
      mode: "outer_frame_v1"
      kernel: "gcc_ca"
      fusion: "concat"
      instance_kernel: "interpolation_bilinear"
      use_pe: True
    activation:
      name: "swish"
  normalization:
    name: "batch_norm_2d"
    momentum: 0.1
  activation:
    name: "swish"
  layer:
    global_pool: "mean"
    conv_init: "kaiming_normal"
    linear_init: "trunc_normal"
    linear_init_std_dev: 0.02
ema:
  enable: true
  momentum: 0.0005
ddp:
  enable: True
  rank: 0
  world_size: -1
  dist_port: 30787
stats:
  name: [ "loss", "top1", "top5" ]
  checkpoint_metric: "top1"
  checkpoint_metric_max: true
