common:
  run_label: "run_1"
  accum_freq: 1
  accum_after_epoch: -1
  log_freq: 200
  auto_resume: true
  mixed_precision: true
  results_loc: "/home/disk/result/segmentation_pascal/edgeformer-s"
dataset:
  root_train: "/home/disk/data/pascal_aug/"
  root_val: "/home/disk/data/pascal_aug/"
  name: "pascal"
  category: "segmentation"
  train_batch_size0: 8
  val_batch_size0: 4
  eval_batch_size0: 4
  workers: 8
  persistent_workers: false
  pin_memory: false
  pascal:
    use_coco_data: True
    coco_root_dir: "/home/disk/data/coco_preprocess/"
image_augmentation:
  random_resize:
    enable: true
    min_size: 384
    max_size: 768
  random_crop:
    enable: true
    mask_fill: 255
    resize_if_needed: true
  random_horizontal_flip:
    enable: true
sampler:
  name: "batch_sampler"
  bs:
    crop_size_width: 512
    crop_size_height: 512
loss:
  category: "segmentation"
  ignore_idx: 255
  segmentation:
    name: "cross_entropy"
optim:
  name: "adamw"
  weight_decay: 0.01
  no_decay_bn_filter_bias: false
  adamw:
    beta1: 0.9
    beta2: 0.999
scheduler:
  name: "cosine"
  is_iteration_based: false
  max_epochs: 50
  warmup_iterations: 500
  warmup_init_lr: 0.00009
  cosine:
    max_lr: 0.0009
    min_lr: 1.e-6
model:
  segmentation:
    name: "encoder_decoder"
    lr_multiplier: 10
    seg_head: "deeplabv3"
    output_stride: 16
    classifier_dropout: 0.1
    activation:
      name: "relu"
    deeplabv3:
      aspp_dropout: 0.1
      aspp_sep_conv: false
      aspp_out_channels: 256
      aspp_rates: [6, 12, 18]
  classification:
    name: "edgeformer"
    classifier_dropout: 0.2
    edge:
      scale: "scale_s"
      mode: "outer_frame_v1"
      kernel: "gcc_ca"
      fusion: "concat"
      instance_kernel: "interpolation_bilinear"
      use_pe: True
    activation:
      name: "swish"
    # pretrained: "/home/disk/result/classification_imagenet1k/edgeformer-s/run_1/checkpoint_ema_avg.pt"
    # pretrained: "./pretrained_models/classification/checkpoint_ema_avg.pt"
  normalization:
    name: "sync_batch_norm"
    momentum: 0.1
  activation:
    name: "relu"
    inplace: false
  layer:
    global_pool: "mean"
    conv_init: "kaiming_normal"
    linear_init: "normal"
    conv_weight_std: false
ema:
  enable: true
  momentum: 0.0005
ddp:
  enable: True
  rank: 0
  world_size: -1
  dist_port: 30788
stats:
  name: [ "loss", "iou"]
  checkpoint_metric: "iou"
  checkpoint_metric_max: true